app = "quest-of-mesh-3"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  WS_PORT = "8081"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
